<div className="Hovermovie" style={{width: 901, height: 865, position: 'relative', background: 'white', border: '1px black solid'}}>
  <div className="NoTimeToDie" style={{left: 34, top: 386, position: 'absolute', color: 'black', fontSize: 24, fontFamily: 'Istok Web', fontWeight: '700', wordWrap: 'break-word'}}>NO TIME TO DIE</div>
  <div className="2h21min" style={{width: 145, left: 34, top: 421, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Istok Web', fontWeight: '400', wordWrap: 'break-word'}}>2021 2h 21min</div>
  <div className="DanielCraigReturnsOneLastTimeAsJamesBondStarringAlongsideOscarWinnerRamiMalekInNoTimeToDieBondHasLeftActiveServiceAndIsEnjoyingATranquilLifeInJamaicaHisPeaceIsShortLivedWhenHisOldFriendFelixLeiterJeffreyWrightFromTheCiaTurnsUpAskingForHelp" style={{width: 835, left: 34, top: 482, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Istok Web', fontWeight: '400', wordWrap: 'break-word'}}>Daniel Craig returns one last time as James Bond, starring alongside Oscar winner Rami Malek in 'No Time To Die'. Bond has left active service and is enjoying a tranquil life in Jamaica. His peace is short-lived when his old friend Felix Leiter (Jeffrey Wright) from the CIA turns up asking for help.</div>
  <img className="Image6" style={{width: 674, height: 305, left: 106, top: 49, position: 'absolute'}} src="https://via.placeholder.com/674x305" />
  <div className="ActorsDanielCraigAnaDeArmasRamiMalekDirectorCaryJojiFukunagaGenresThrillersActionAdventurePrice1499Week" style={{left: 32, top: 636, position: 'absolute'}}><span style="color: 'black', fontSize: 20, fontFamily: 'Istok Web', fontWeight: '700', wordWrap: 'break-word'">Actors:</span><span style="color: 'black', fontSize: 20, fontFamily: 'Istok Web', fontWeight: '400', wordWrap: 'break-word'"> Daniel Craig, Ana de Armas, Rami Malek  </span><span style="color: 'black', fontSize: 20, fontFamily: 'Istok Web', fontWeight: '700', wordWrap: 'break-word'">Director:</span><span style="color: 'black', fontSize: 20, fontFamily: 'Istok Web', fontWeight: '400', wordWrap: 'break-word'"> Cary Joji Fukunaga  </span><span style="color: 'black', fontSize: 20, fontFamily: 'Istok Web', fontWeight: '700', wordWrap: 'break-word'">Genres:</span><span style="color: 'black', fontSize: 20, fontFamily: 'Istok Web', fontWeight: '400', wordWrap: 'break-word'"> Thrillers, Action & Adventure<br/></span><span style="color: 'black', fontSize: 20, fontFamily: 'Istok Web', fontWeight: '700', wordWrap: 'break-word'">Price: 14.99$/WEEK </span></div>
  <div className="Rectangle10" style={{width: 201, height: 48, left: 32, top: 773, position: 'absolute', background: '#D9D9D9'}} />
  <div className="AddToCart" style={{left: 47, top: 784, position: 'absolute', color: 'black', fontSize: 24, fontFamily: 'Istok Web', fontWeight: '700', wordWrap: 'break-word'}}>ADD TO CART</div>
  <div className="Rectangle11" style={{width: 201, height: 48, left: 32, top: 773, position: 'absolute', background: '#D9D9D9'}} />
  <div className="Rectangle12" style={{width: 257, height: 48, left: 304, top: 771, position: 'absolute', background: '#D9D9D9'}}></div>
  <div className="AddToCart" style={{left: 50, top: 779, position: 'absolute', color: 'black', fontSize: 24, fontFamily: 'Istok Web', fontWeight: '700', wordWrap: 'break-word'}}>ADD TO CART</div>
  <div className="AddToWishlist" style={{left: 326, top: 777, position: 'absolute', color: 'black', fontSize: 24, fontFamily: 'Istok Web', fontWeight: '700', wordWrap: 'break-word'}}>ADD TO WISHLIST</div>
</div>